apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ecomm
spec:
  selector:
    app: product
  ports:
    - port: 80          # External service port (keep as 80 ✅)
      targetPort: 8000  # ✅ FIXED → maps to container 8000
  type: ClusterIP
